menu:
  Home: /
  Archives: /archives
  # About: /about

widgets:
- search
- category
- tag
# - twitter

excerpt_link: Read more

github:
  username:

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: false
  twitter: true
  google: false
  pinterest: false

fancybox: true

google_analytics:
domain:

rss:
